---
# tasks file for Debian
- name: Check if godeb is installed
  become: true
  stat: path=/usr/bin/godeb
  register: godeb_check

- name: create temporary directory
  when: godeb_check.stat.exists == False
  become: true
  tempfile:
    state: directory
    suffix: godeb
  register: golang_temp

- name: set perms on temp directory
  when: godeb_check.stat.exists == False
  become: true
  file: 
    path: "{{ golang_temp.path }}"
    mode: 0777

- name: Download godeb
  when: godeb_check.stat.exists == False
  become: true
  get_url: 
    url="https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz"
    dest="{{ golang_temp.path }}/godeb-amd64.tar.gz"

- name: create temporary extracted directory
  when: godeb_check.stat.exists == False
  become: true
  tempfile:
    state: directory
    suffix: godeb-extracted
  register: golang_temp_extracted

- name: Extract godeb
  when: godeb_check.stat.exists == False
  become: true
  unarchive:
    src: "{{ golang_temp.path }}/godeb-amd64.tar.gz"
    dest: "{{ golang_temp_extracted.path }}"

- name: Install godeb
  when: godeb_check.stat.exists == False
  become: true
  command: "mv {{ golang_temp_extracted.path }}/godeb /usr/bin/godeb"