---
- name: Set default shell to zsh
  become: no
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Install antigen
  become: no
  git:
    repo: "https://github.com/zsh-users/antigen.git"
    dest: "~/.antigen"
    version: v2.2.3

- name: ensure .zshrc
  become: no
  file:
    path: "~/.zshrc"
    state: touch
    mode: 0644

- name: .zshrc sources .profile
  become: no
  blockinfile:
    path: "~/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bashrc"
    insertbefore: BOF
    block: |
      source "${HOME}/.profile"

- name: Configure antigen
  become: no
  blockinfile:
    path: "~/.zshrc"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - antigen"
    block: |
      source ~/.antigen/antigen.zsh
      # For tilix
      if [[ $TILIX_ID ]]; then
        source /etc/profile.d/vte.sh
      fi
      # Load the oh-my-zsh's library.
      antigen use oh-my-zsh
      # Bundles from the default repo (robbyrussell's oh-my-zsh).
      antigen bundle git
      antigen bundle command-not-found
      # Syntax highlighting bundle.
      antigen bundle zsh-users/zsh-syntax-highlighting
      antigen bundle zsh-users/zsh-completions
      antigen bundle supercrabtree/k
      # Powerlevel9k Theme
      POWERLEVEL9K_INSTALLATION_PATH=~/.antigen/bundles/bhilburn/powerlevel9k
      antigen theme bhilburn/powerlevel9k powerlevel9k
      POWERLEVEL9K_MODE='nerdfont-complete'
      POWERLEVEL9K_PROMPT_ON_NEWLINE=true
      POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
      POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
      DEFAULT_USER=$(whoami)
      # Tell antigen that you're done.
      antigen apply
