# distrobox assemble create --file ~/.config/distrobox/citrix-zoom.ini
[citrix-zoom]
image=citrix-zoom:latest
unshare_groups=true
unshare_ipc=true
unshare_netns=true
unshare_process=true
nvidia=false
pull=false
root=false
replace=true
start_now=true
init_hooks=whoami | xargs sudo usermod -a -G adm

exported_bins=/opt/Citrix/ICAClient/wfica
