---
- name: Install asdf-vm
  become: no
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "~/.asdf"
    version: v0.7.2

- name: Add asdf-vm to shell
  become: no
  blockinfile:
    path: "~/.profile"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - asdf"
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash

- name: Add asdf-vm plugins
  loop: "{{ user.asdf.plugins|dict2items }}"
  loop_control:
    label: "{{ item.key }}: {{ item.value }}"
  become: no
  shell: . ~/.asdf/asdf.sh && asdf plugin-add {{ item.key }} {{ item.value }}
  args:
    creates: ~/.asdf/plugins/{{ item.key }}
    executable: /bin/bash
