---
- name: Set default shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  ignore_errors: yes

- name: Install Oh My ZSH
  become: no
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "~/.oh-my-zsh"

- name: Install ZSH Plugins
  become: no
  git:
    repo: "{{ item.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
  loop:
    - repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      name: "zsh-syntax-highlighting"
    - repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      name: "zsh-autosuggestions"
    - repo: "https://github.com/chrissicool/zsh-256color.git"
      name: "zsh-256color"

- name: ZSH Theme
  become: no
  git:
    repo: "https://github.com/bhilburn/powerlevel9k.git"
    dest: "~/.oh-my-zsh/custom/themes/powerlevel9k"
    depth: 1

- name: ensure .zshrc
  become: no
  file:
    path: "~/.zshrc"
    state: touch
    mode: 0644

- name: .zshrc sources .profile
  become: no
  blockinfile:
    path: "~/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bashrc"
    insertbefore: BOF
    block: |
      source "${HOME}/.profile"


- name: Copy .zshrc.d files
  become: no
  synchronize:
    src: "{{ role_path }}/files/.zshrc.d/"
    dest: "~/.zshrc.d"

- name: Configure zshrc
  become: no
  blockinfile:
    path: "~/.zshrc"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - zshrc"
    block: |
      source ~/.zshrc.d/init.zshrc
