---
- name: Set default shell to zsh
  become: no
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Install zplug
  become: no
  git:
    repo: "https://github.com/zplug/zplug.git"
    dest: "~/.zplug"
    version: master

- name: ensure .zshrc
  become: no
  file:
    path: "~/.zshrc"
    state: touch
    mode: 0644

- name: .zshrc sources .profile
  become: no
  blockinfile:
    path: "~/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bashrc"
    insertbefore: BOF
    block: |
      source "${HOME}/.profile"

- name: Configure zplug
  become: no
  blockinfile:
    path: "~/.zshrc"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - zplug"
    block: |
      source ~/.zplug/init.zsh
      zplug "zsh-users/zsh-history-substring-search"
      zplug "chrissicool/zsh-256color"
      zplug "plugins/git",   from:oh-my-zsh
      zplug "plugins/pip",   from:oh-my-zsh
      zplug "plugins/command-not-found",   from:oh-my-zsh
      zplug "zsh-users/zsh-syntax-highlighting"
      zplug "zsh-users/zsh-completions"
      zplug "supercrabtree/k"
      zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
      POWERLEVEL9K_MODE='nerdfont-complete'
      POWERLEVEL9K_PROMPT_ON_NEWLINE=true
      POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
      POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
      DEFAULT_USER=$(whoami)
      # Install plugins if there are plugins that have not been installed
      if ! zplug check; then
        echo; zplug install
      fi
      # Then, source plugins and add commands to $PATH
      zplug load
