---
- name: Set default shell to zsh
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  become: yes
  user:
    name: "{{ item.name }}"
    shell: /usr/bin/zsh

- name: Install antigen
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  become: "{{ item.name }}"
  git:
    repo: 'https://github.com/zsh-users/antigen.git'
    dest: "~/.antigen"
    version: v2.2.3

- name: ensure .zshrc
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  become: "{{ item.name }}"
  file:
    path: "~/.zshrc"
    state: file
    mode: 0644

- name: .zshrc sources .profile
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  become: "{{ item.name }}"
  blockinfile:
    path: "~/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - bashrc"
    insertbefore: BOF
    block: |
      source "${HOME}/.profile"

- name: Configure antigen
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  become: "{{ item.name }}"
  blockinfile:
    path: "~/.zshrc"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - antigen"
    block: |
      source ~/.antigen/antigen.zsh
      # Load the oh-my-zsh's library.
      antigen use oh-my-zsh
      # Bundles from the default repo (robbyrussell's oh-my-zsh).
      antigen bundle git
      antigen bundle git-flow
      antigen bundle pip
      antigen bundle command-not-found
      # Syntax highlighting bundle.
      antigen bundle zsh-users/zsh-syntax-highlighting
      antigen bundle zsh-users/zsh-completions
      antigen bundle rimraf/k
      # Load the theme.
      POWERLEVEL9K_INSTALLATION_PATH=~/.antigen/bundles/bhilburn/powerlevel9k
      antigen theme bhilburn/powerlevel9k powerlevel9k
      POWERLEVEL9K_MODE='awesome-fontconfig'
      POWERLEVEL9K_PROMPT_ON_NEWLINE=true
      POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
      POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
      DEFAULT_USER=$(whoami)
      # Tell antigen that you're done.
      antigen apply


