---
- name: User global gitconfig
  become: no
  blockinfile:
    create: yes
    path: "~/.gitconfig"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - global"
    block: |
      [core]
        editor = {{ user.git.config.global.core.editor }}
      [user]
        name = {{ user.git.config.global.user.name }}
        email = {{ user.git.config.global.user.email }}
        {% if user.git.config.global.user.signingkey %}
        signingkey = {{ user.git.config.global.user.signingkey }}
        {% endif %}

- name: Configure extra Git config
  include_tasks: user-extra.yml
  when: user.git.config.extra is defined
