---
- name: User extra directory
  become: no
  loop: "{{ user.git.config.extra }}"
  loop_control:
    label: "{{ item.path }}"
  file:
    path: "{{ item.path }}"
    state: directory

- name: User Write extra .gitconfig
  become: no
  loop: "{{ user.git.config.extra }}"
  loop_control:
    label: "{{ item.path }}"
  blockinfile:
    create: yes
    path: "{{ item.path }}/.gitconfig"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.path }}"
    block: |
      [user]
        name = {{ item.user.name }}
        email = {{ item.user.email }}
        {% if item.user.signingkey is defined %}
        signingkey = {{ item.user.signingkey }}
        {% endif %}

- name: User Include extra .gitconfig
  become: no
  loop: "{{ user.git.config.extra }}"
  loop_control:
    label: "{{ item.path }}"
  blockinfile:
    create: yes
    path: "~/.gitconfig"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.path }}"
    block: |
      [includeIf "gitdir:{{ item.path }}/"]
        path = {{ item.path }}/.gitconfig
