---
- name: Gather the package facts
  package_facts:
    manager: auto

- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Setup User
  include_tasks: user-gnome.yml
  when: user is defined and ansible_os_family == 'Debian' and 'gnome-desktop' in ansible_facts.packages
