---
- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
  
- name: Setup User
  include_tasks: user.yml
  when: user is defined
