---
# tasks file for base-packages
- name: Install base packages
  become: true
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - curl
      - htop
      - iotop
      - nmap
      - colordiff
