---
- name: Configure default CLI editor
  become: no
  blockinfile:
    path: "~/.profile"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - editor"
    block: |
      export EDITOR=vim

# TODO: gpg
